# Generated by Django 3.1.1 on 2020-10-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detr',
            new_name='dest',
        ),
    ]
